### ISSUE TITLE
Previously downloaded issues are deleted during connectivity issues

### ISSUE THREAD

**Issue by rogerdcarvalho** [bakerframework/baker#35]
Hi,

In the latest master, using MagRocket backend 1.0, if you open the app while you are technically 'online', but without full internet access (e.g. a wifi hotspot that requires login or 3G access without prepaid credit), baker opens with an empty white screen (I presume it is trying to connect to magrocket to see if there are new issues available). This can take quite a while. If you tap the 'refresh' button during this white screen, Baker forgets any previously downloaded issues. This means that when you open the app again, you have to re-download any issues you had before. 

Can we prevent Baker from ever 'forgetting' previously downloaded issues, and is there a way to reduce the time-out for trying to connect to magrocket before showing the existing shelf?

**Comment by GennadyK** [comment]
[BKRBakerAPI.m.zip](https://github.com/bakerframework/baker/files/664827/BKRBakerAPI.m.zip)

I remember that this exact bug deferred us from using Baker ~2 years ago when suddenly everything  disappeared from the shelf. But we weren't as determined then as now :) 
So this is the fix for that nasty bug in case of use of backend with a JSON file:

1. Find in file BKRBakerAPI.m, function getFromURL this code:
else if ([response statusCode] == 200) {
        return data;
    }

And replace it with:
else if ([response statusCode] == 200) {
        NSRange range = {0, 22};    // to check if beginning 22 bytes of shelf.json include '"name":'
        NSData *beginningBytes;
        beginningBytes = [data subdataWithRange:range];
        NSString *dataString = [[NSString alloc] initWithData:beginningBytes encoding:NSUTF8StringEncoding];
        //NSLog(@"[DEBUG] dataString inside of getFromURL(BKRBakerAPI.m): %@",dataString);
`        if ([dataString rangeOfString:@"\"name\":"].location == NSNotFound) {`
            NSLog(@"[ERROR] Failed GET request - bad shelf.json structure");
            return nil;
        } else {
            return data; // has '"name":', so it's a valid shelf.json
        }
    }

This added code is checking if returned data has shelf.json structure in it:
[
  {
    "name": "book1-name",
...

Now nothing gets deleted in case of the connectivity problem:
Before books were deleted:
...
2016-12-07 18:09:12.401402 Baker[373:40341] [BakerShelf] Newsstand - Removed book1-name
...

And now cached shelf.json is used:
...
2016-12-07 20:54:11.920058 Baker[455:65983] [ERROR] Failed GET request - bad shelf.json structure
2016-12-07 20:54:11.920565 Baker[455:65927] [BakerShelf] Loading cached Shelf manifest from /var/mobile/Containers/Data/Application/32F8A49B-2154-4C2B-8EC4-D22C885CF776/Library/Caches/shelf.json
...
