### ISSUE TITLE
Where is Tutorial Baker 4.3 

### ISSUE THREAD

**Issue by Marzio1** [bakerframework/baker#402]
Where can I find a tutorial for new opportunities Baker 4.3?
- Support for categories in the shelf view
- Full support as a Universal app
- Newsstand icon is now updated dynamically
- Autoplay on UIWebView is now allowed
- Settings are now defined in the settings.plist file instead of code
- Change to the way the header in the shelf view works
- Many new config settings to customize the shelf

**Comment by luckyman24** [comment]
Hey marzio1, how did you realized the android version? which framework do you use? BR, Michael

**Comment by tobiasstrebitzer** [comment]
@luckyman24 @Marzio1 i'm also curious which android version you have been using. I've just pushed a refactor of the android app to github (https://github.com/bakerframework/baker-android-refactor), with initial support for categories, paid issues and subscriptions, maybe that's helpful.

**Comment by Marzio1** [comment]
Currently I published Android versions of  Magazines with Android Studio Mac Version 0.8.4 and BakerAndroid (september 2014)

**Comment by alemachado** [comment]
hi @tobiasstrebitzer first of all, congratulations for the framework!

I'm trying to work on my first project using baker and It's mandatory to organize the issues on it. So maybe the categories filter should help (even if a search field would be perfect).
The problem is that when I try to Build and Run on a device, after clicking on the categories dropdown the app returns an exception:

> "Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of items in section 0.  The number of items contained in an existing section after the update (2) must be equal to the number of items contained in that section before the update (2), plus or minus the number of items inserted or deleted from that section (0 inserted, 1 deleted) and plus or minus the number of items moved into or out of that section (0 moved in, 0 moved out).'"

Have you any idea what is going on?

thanks again
