### ISSUE TITLE
Is there a way to embed fonts?

### ISSUE THREAD

**Issue by codegeek511** [bakerframework/baker#415]
We have used some fonts in our magazines and they show on the html in out computers but not on the other devices. Is their a way to embed the fonts?

Thanks

**Comment by AlexAlmond** [comment]
The best way is to use web fonts is to store/load them locally from your hpub package. You can use http://www.fontsquirrel.com/tools/webfont-generator to generate any web fonts. But note that they may be subject to copyright and some may not convert due to this.

Once you download your generated files you can use the css included in the package to help load the fonts for devices.
