### ISSUE TITLE
1 year Subscription giveaway

### ISSUE THREAD

**Issue by reefmag** [bakerframework/baker#423]
Hi,
I currently have paid subscriptions and issues.
I want to do a giveaway, for example, Giveaway a 1 year subscription. 
Is this possible to do with Baker? I am not sure how to set up someone, specifically the winner with a subscription.

Hopefully there is a way to make this work.

**Comment by codegeek511** [comment]
I have seen this question asked before a while back and it could not happen. Could be different now though. I know this is different but you can change the price to free in iTunes Connect for a limited time.

**Comment by reefmag** [comment]
OK. I'll have to try that. Thanks for the reply!

**Comment by MagLoftMagazines** [comment]
Currently you would have to manually input a record in your subscriptions table, but then again I am not sure if BC even checks that? I seem to remember the receipt is checked on every call or at least quite often. 

For this to really work, we need a login to the Baker app so that the backend can give access to issues for that particular user. This is something we will be working on soon, but until then, there is no way to offer a free year subscription with Baker and Baker Cloud Edition.

**Comment by reefmag** [comment]
No prob. Thanks Nick!

**Comment by pieterclaerhout** [comment]
If you would opt to use Twixl Publisher (http://twixlmedia.com), we have an option called "Entitlements". This allows you to provide a user with a login, promo code or access key which would grant them free access to one or more issues.

Kind regards,


Pieter, Lead Developer @ Twixl media


> Op 20-feb.-2015 om 03:16 heeft reefmag <notifications@github.com> het volgende geschreven:
> 
> No prob. Thanks Nick!
