### ISSUE TITLE
Communication between Xcode and BakerCloud

### ISSUE THREAD

**Issue by PMCor** [bakerframework/baker#426]
Hi there, i've been working on a new project which includes a newsstand app and i found a barrier that i've been trying to figure how to workaround. I've managed to get Xcode to get issues from my own server (which i have baker console installed) through shelf.json but what i want is to know how is made the communication between xcode and baker console so i can control who downloaded the app and paid. Also if the person who paid the app deletes i want to know if it can restore the subscription.

Any chance i can get some help on how to configure the baker cloud communication with Xcode?

Thanks in advance!

**Comment by MagLoftMagazines** [comment]
This would require a login feature in the Xcode app as Apple doesn't give you this information.

As for restore purchases, this is already done by the Baker app, but you need to offer paid subscriptions/issues for it to show up.

**Comment by MagLoftMagazines** [comment]
Apple doesn't make this information available. There needs to be a login feature in Baker, that will then send this information to the backend server, so it's possible to pair the user_id from the app with the user_id in the backend. This is a very old feature request but as far as I know no one has started it yet.

We are starting development of this feature so that MagLoft powered Baker apps can login with Facebook or email/password.

**Comment by PMCor** [comment]
First of all thanks for the answer Nick. As far as my problem resolution i got it done after a few hours of digging! Thanks again for the answer.
