### ISSUE TITLE
open hpub in xcode project

### ISSUE THREAD

**Issue by AlmondFace** [bakerframework/baker#428]
Hi, 

i have created a valid hpub and want to open it in my app without having to upload it to my server and download into the app each time. Any help on how to do this would be great.

thanks

**Comment by MagLoftMagazines** [comment]
I suggest you have a second Xcode project that uses the standalone mode. Then all you have to do is unzip your HPUB and drop the contents into it's own folder under the /books folder in xcode. See how it's done with the "Scarlet" book that is already in there when you download Baker.

In order to use the standalone mode, you simply set the "is Newsstand" option in the settings.plist in Baker to false.

**Comment by AlmondFace** [comment]
Thanks Nick, this is perfect, i knew there must be a simple way but was looking to over complicate the situation, thanks :)
