### ISSUE TITLE
my book is crashing

### ISSUE THREAD

**Issue by nevoeiro** [bakerframework/baker#429]
Hi there,

I'm developing a digital book based on baker 4.3. The book has 40 pages and each page has a background image that show a 1024x768 for non retina devices and 2048x1536 for retina. I have 20 pages with video and 2 pages with a gallery (4 images each).
As I see, when I start my app everything is ok and when I navigate between some pages I see RAM increase and increase and then the app crash. If I return to the app I swipe some pages and it crash again. If I shutdown the app and start again it crashes after swipe some pages too.

I don't know what can I do to resolve this. Maybe you can help me. Any suggestions?

Thanks.

Best regards

**Comment by MagLoftMagazines** [comment]
What size are these images in MB?

**Comment by nevoeiro** [comment]
Retina images 2048x1536 - size between 900KB and 2MB
Non retina 1024x768 - size between 100KB and 1MB

Thanks for helping

**Comment by tobiasstrebitzer** [comment]
Two more questions:
* What devices did you test your app on?
* What filesize / filetype are your videos?

Here's some suggestions to get to the source of the problem:
* Try to use the [screenshots rendering mode] (https://github.com/Simbul/baker/wiki/Baker-rendering-modes). By default, baker will load up to three pages at once (previous and next pages). This forces the app to allocate three times the amount of memory, and might exhaust your device especially when navigating quickly.
* Try to temporarily remove all videos from your book. This is obviously not a solution, but it might pinpoint the memory problem. If it's working well without the videos, you'll know that your videos are causing the memory exhaustion. In that case you can try to reduce the quality / filesize of the videos, or change the encoding. Are your videos packed into the book, or are you using remote videos (like youtube iframe / vimeo / etc...).
* If you're willing to share your book, i'd like to run a memory profile.

**Comment by nevoeiro** [comment]
My app is designed only for iPad.

1) We tested in all iPad simulators and everything is ok. When we tested on iPad Air the book crash after swipe some pages.

2) All videos are packed into the book. The file size of videos varies between 9 MB to 126 MB. The total size (18 files) is 464MB. File type is mp4.

I'll try your suggestions and then I give you my feedback. Then I can share the book with you. Thank you very much.

Regards

**Comment by nevoeiro** [comment]
Hi
I used screenshots rendering mode and removed all pages that contain video. The problem continue, I didn't see any improvements.

tobiasstrebitzer, please give me your email to share the book with you.

Thanks.

**Comment by tobiasstrebitzer** [comment]
my email is toby@magloft.com

Are you using the latest version of baker, and/or have there been any customizations in the app besides changing assets, settings and variables?

Kind Regards

**Comment by nevoeiro** [comment]
OK, thank you.

I sent you the project by wetransfer. You must receive that in a few minutes.
I'm using the latest version of baker and I didn't any customization. That was a clean install of baker 4.3 and configured to a standalone app.

Thanks for helping. 
King regards

**Comment by tobiasstrebitzer** [comment]
Hi @nevoeiro 

I've had a first look at your issue, and although it didn't crash for me in simulator and device, i've seen the memory going nuts.

Two observations so far:

1. The render-type is set to "screenshots" (showing previews of the page before webkit renders the actual page). most of the allocated memory is coming from these screenshots, as they seems not to be released when navigating away. When navigating further and further, memory stacks up and is likely to crash your app. Switching to "three-cards" (rendering both previous and next page contents in webview) makes the memory allocation less exponential, but still it seems like it's bulking up, not releasing some of the memory. Changing to this rendering mode might fix your issue, but it's still consuming too much memory (i was going up to 600-700mb), which will in the end crash at least older devices.

2. Although the images you're using are not overwhelmingly large in filesize, i've checked and saw that most of your images can be compressed further down (using free services like tinyjpg) to more than 50%. It's not the 'native' cause of your problem, but compressing down further will optimize both the memory usage, as well as the overall filesize of your hpub, leading to shorter download-times for your readers. If you're willing to compress the images, i'd like to profile your app once more to see the impact of these optimizations on memory usage.

3. There's definitely some more memory problems, which i haven't been able to find for now. I hope it's not caused by your html/js, as that would expose webkit of leaking memory, which we're not really in control of. End of this week i'll investigate further.

Shouting out to @pieterclaerhout about any eventual observations.

Cheers, Toby

**Comment by pieterclaerhout** [comment]
Hi @tobiasstrebitzer and @nevoeiro, can you provide me with a copy of the hpub files? You can send it to pieter@twixlmedia.com.

**Comment by nevoeiro** [comment]
Hi
@tobiasstrebitzer thank you for your analysis and suggestions. 
I'll test with three-cards render type and see what happens on my device. Then I'll apply more compression to images and test again. 
What about the videos? Do you think they're ok or it is better to optimize them too? I did a test without video pages but the problem continue so I think the source of this problem is other.
@pieterclaerhout I sent you an email with the same file I sent to tobias. 

Thank you.

Best regards

**Comment by tobiasstrebitzer** [comment]
hi @nevoeiro,

great! The videos are definitely not an issue, as they are loaded only when the video-links are pressed. Optimizing video size will reduce the overall download size of your issue, which is generally a good idea, especially for issues containing many pages as yours.

Great job on the design btw.

**Comment by robsonw** [comment]
Hi

I'm experiencing this issue since version 4.1. After the ARC update the system appears more stable, but this issue is still there.

If you see the log inside Xcode, you will see a lot of "Received memory warning".
- using screenshots or three-cards
- using big images (1024x768 is not so big) or just normal html with some images and youtube videos
- using old and new iPad (like iPad Air 2)
- also occurs on the return of ModalView

I did some investigations on the code and I don't think the issue is with the book, but with the memory allocation of the Views and UIWebView.

I tested some changes on didReceiveMemoryWarning, but this don't solve the issue root cause. 

```
- (void)didReceiveMemoryWarning {
    // Releases the view if it doesn't have a superview.
    [nextPage removeFromSuperview];
    [prevPage removeFromSuperview];
    [super didReceiveMemoryWarning];
    // Release any cached data, images, etc that aren't in use.
}
```

The code above is inside BakerViewController.m and now in BKRBookViewController.m.
I imagine to dismiss the pages after a Memory Warning, and reload the pages after the dismissing. The reload part is not working correctly. This is not the best solution since it doesn't solve the root cause of the issue, because Memory Warnings still will be occurring frequently.

Maybe you have a better solution or some ideas. Hope this report help us to solve this issue.

**Comment by nevoeiro** [comment]
Hi

@robsonw thanks for sharing your experience. 
You're right, I had already compressed all the images and videos and when I tested again I didn't see major improvements on the performance. The difference was instead of crashing from page 7, it started crashing from page 11. Then I thought the problem was on my html/js code, I tried to test various scenarios but I didn't success on my experiences.

I'll test your code suggestion and see what happens. I hope @pieterclaerhout has a better opinion or solution for this issue. 
Otherwise I'll explore baker code with more detail or change my book framework.

**Comment by nevoeiro** [comment]
Hi

@tobiasstrebitzer 
1) I already made all the compressions on images. I save about 40% on images size and I see some improvements loading the views. But book continue crashing after page 8/9 on my device.

2) I changed rendering mode to three-cards and I can read the book until page 25/26 and then it crash

3) I tried @robsonw code and the book crash after page 31/32 

Thanks.

Best regards

**Comment by nevoeiro** [comment]
Hi

After update our device to iOS 8.2 and run the book again, the problem was gone and everything works well now. Before we have >400MB of RAM consumed by the app, now the values are between 30-80MB.
Thanks @tobiasstrebitzer and @pieterclaerhout for helping us with this issue.

Best regards

**Comment by tobiasstrebitzer** [comment]
Thanks @nevoeiro, glad this issue is solved! Some of your readers might still experience this problem, running older iOS versions, but time is working for you :-)
