### ISSUE TITLE
How to display content for iPad and iPhones

### ISSUE THREAD

**Issue by billybaughman** [bakerframework/baker#444]
I created a magazine that was going to just be available for iPad. I got a bit tired of hearing from people that have iPhones say they can't find the magazine. So I updated Baker to include iPhones. Unfortunately, my magazines lay out is designed for iPad and doesn't fit the iPhone dimensions.

I don't want to use a liquid layout so, if need be, will create an iPad version and an iPhone version of the issues. Is there a (easy, non-programmer) way to detect which device is being used and to download the appropriate hpub file? Or is there some other way to make this work?

I was thinking I could create two apps, one for the iPad and one for the iPhone. My only issue is that if someone subscribes to one version it won't transfer to the other.

FYI: I use Indesign and In5 to design my magazine.

Billy

**Comment by AlexAlmond** [comment]
You can look to set up your JSON to download one package from your ftp for iPhone, and another for iPad. If you use Baker Cloud then this probably wouldn't be possible as these keys are not in the CMS. I manually write my JSON so that i can do this.

If you wanted to take this approach then you would need to detect the device with some objective-c, and then once your app has confirmed the device type, link to the appropriate package.

**Comment by billybaughman** [comment]
Thanks, Alex!

**Comment by AlexAlmond** [comment]
No worries, ive literally just released on of our latest magazines which is free to download and downloads one package for iPhone, and another for iPad. Check it out here: https://itunes.apple.com/app/the-periodic-journal/id969291361?mt=8

**Comment by Kaze919** [comment]
@AlexAlmond Would you be able to post your code to allow for detection of the device and what JSON modifications would need to be made. I'm sure modifying the CMS could be possible to use Baker CE to just add additional forms. Thank you.
