### ISSUE TITLE
Standalone App with ability to download new issues

### ISSUE THREAD

**Issue by dtron5** [bakerframework/baker#470]
Hi there.

Really hoping you can help.

Is it possible to create a stand alone version of a magazine app that allows downloading of new issues to the shelf?  (Free app and free issues)

I've discovered I can put multiple 'books' in the books folder to get a shelf view showing every book. However, I'd like to be able to have new issues show on the shelf with the download button. I'd modify the shelf.json file on a server whenever a new book is available.

Is this possible. If so how

Thanks for you thoughts

David

**Comment by dtron5** [comment]
I may have answered my own question

I've discovered that if I  change a setting in the info.plist where 'Required background modes' is set to 'App downloads content from the network', the test app sits outside of newsstand where I want it

I don't really know if it's a valid solution.

**Comment by MagLoftMagazines** [comment]
It will work, but currently the Newsstand Framework does not work outside of Newsstand. This means you will not be able to push new issues via a backend, and start the download of issues. This kind of defies the whole idea :) The standalone version only supports content from the books folder inside your Xcode app, which means, in order to push a new issue/book you would have to include it in your Xcode, archive and submit a new version.

Lastest news from Apple is, they will do away with the Newsstand in iOS9 and all Newsstand apps will become standalone apps instead, which is a good thing :)

**Comment by dtron5** [comment]
Thanks Martin. Really appreciate you taking the time to reply

I'm sure I got it to download issues yesterday but it doesn't seem to work today. Maybe I just imagined it. What was in that coffee?

Good news about iOS9. Will Baker be updating the framework to accomadate this or will it just happen as a default, ie present the app to the desktop

Thanks

**Comment by tobiasstrebitzer** [comment]
Hi @dtron5,

i've seen a video that shows newsstand apps working outside of newsstand as 'regular apps' in iOS 9. Most likely there is no change to your app required (before iOS9, the NewsstandKit framework which is required for issue downloads etc... was not allowed outside the newsstand folder).

We'll do some first tests on iOS 9 shortly.

Cheers, Toby

**Comment by dtron5** [comment]
Thank you Tobias

That will be fantastic. I look forward to seeing the results of your testing 

Thanks

David
