### ISSUE TITLE
Existing standalone app to newsstand

### ISSUE THREAD

**Issue by snowywolfie** [bakerframework/baker#481]
I have an existing app published on App Store which have many in-app products. I have few questions in my mind before I publish my newsstand app.  I will be appreciate if anyone could help me.

1.What will happened to my existing app if I enabling the newsstand and publish the newsstand app? 
2.Will it affect the customer that already purchased my in-app product ? 
3.Will Appstore make change / reset the app's download rate and download link to my app?

**Comment by MagLoftMagazines** [comment]
Hi @snowywolfie these are some really great questions! I'll give my two cents and encourage everyone else to pitch in. I personally haven't taken a published standalone into Newsstand so not 100% sure about the answers.

1) Your app will reside inside the Newsstand "folder" and will no longer be visible on the home page of devices.
2) My best guess here is no. The backend you are using should store all receipts and purchase information. In any case, Apple has this information, and you should be able to do a "Restore Purchases" to trigger all the receipts and reactivate purchased issues.
3) I wouldn't think so.

With all that said, you might want to reconsider moving your app inside Newsstand. When iOS9 get's launched they will replace the Newsstand with the new News App. The Newsstand will turn into a regular folder and Newsstand apps become standalone apps. I wrote a short recap of the changes on our blog here: http://blog.magloft.com/apple-kills-newsstand/

Hope others pitch in to give you better answers :)

**Comment by snowywolfie** [comment]
Thank you for your informations, @MagLoftMagazines ! 
But I have one more question, can I still publish Newsstand App in iOS 9 as standalone app with Baker Framework? (With same codes, project settings and etc)

**Comment by MagLoftMagazines** [comment]
Here is what we know for sure. If you were to install iOS9 today (developers can beta it) you would see Baker Newsstand apps as standalone apps in a regular folder. So Baker still works, but we are still waiting for instructions from Apple on how to prepare newsstand apps for iOS 9. We will most likely have to remove the Newsstand Kit from Xcode and replace it with relevant code. 

Basically just create "regular apps" instead of Newsstand apps, as these will probably go away. Maybe Apple will add specific features to magazine type apps, but I doubt that.

We at MagLoft are already converting Baker to standalone app, as we wanted to offer standalone apps that support subscriptions, push, etc. Once we are done, we will push changes to Baker for everyone to use, unless of course someone is already working on this and could get it done sooner?

**Comment by snowywolfie** [comment]
Thank you for your explanation. Now I know how to explain to my client for this coming changes. 
Looking forward to the new Baker Framework and thanks again for this open source project. It really save a lot of times for development and simple to use . :+1:
