### ISSUE TITLE
Separate iPad vs iPhone download requests

### ISSUE THREAD

**Issue by Kaze9** [bakerframework/baker#496]
I'm trying to follow the classes in Xcode but I'm running around in circles as Obj-C isn't my area of expertise. I'm using the external Baker CE to handle my JSON files but I'd like to provide 2 download urls that are delegated based on the device being used.

I realize I'd have to modify the CE as well but I can't figure out where to place a call to check which device is in use. I'd like it to just be if iPad url1 ... else url2

Is there a clean way to implement this in the project file?

**Comment by MagLoftMagazines** [comment]
Hi @Kaze919,

The cleanest way is to let the backend handle this 100%. We have already updated this at MagLoft, so it's now possible to upload an iPhone and iPad version. I'm pretty sure it would be a fairly simple implementation for the Baker CE, but I'll have to leave that up to @nin9creative :)

**Comment by nin9creative** [comment]
Yeah, I know that this is a feature that has been requested.  Basically there needs to be two fields in BakerCE that have different download endpoints.  However there would need to be some changes to the Shelf.JSON spec to have multiple device URL's in that case and Baker would need to handle it.

Otherwise perhaps a better way would be for the Baker app to send the device type to the API calls, and the internal API logic could determine which url to return.

@MagLoftMagazines how did you guys resolve it on your end?

**Comment by MagLoftMagazines** [comment]
Hi @nin9creative,

We let our backend handle which issue is delivered based on the device type that Baker already sends to the end point. With the CE all you need is an additional field for a second HPUB URL and then some logic that tells the server which URL to return.

**Comment by nin9creative** [comment]
I don't know what I was smoking on my initial last comment...  LOL

Looking back at my notes and to/do's - that was what I was going to do on the CE side.  Modify the URL field and then introduce logic to react based on the device type.

**Comment by MagLoftMagazines** [comment]
Cool!

**Comment by Kaze919** [comment]
So this is simply something which can be modified within the CE and the Xcode file doesn't need to be changed?

**Comment by MagLoftMagazines** [comment]
Yup :)

**Comment by Kaze919** [comment]
Making PDFs is gonna be so much easier than trying to make responsive html pages look good.

Anxious to see the fix

**Comment by omegah3** [comment]
How can this be done for none coders like me.
Can someone give a detailed instruction on doing this ?

Thank you all

**Comment by nicholasmartin** [comment]
Hi @omegah3 I think detailed instructions for a non-coder won't matter too much, as you need to write code in order to get this accomplished. The Baker Cloud CE needs to be edited both in the scripts and in the database to support two versions. Not sure if @nin9creative or someone else has played around with these changes in Baker yet?

We have it implemented in MagLoft.com and now we are getting requests to support Android tablet and phones as well as they are slightly different lol. So in total we will have 4 versions of each issue available to use.
