### ISSUE TITLE
Baker framework future

### ISSUE THREAD

**Issue by ahvink** [bakerframework/baker#521]
Just recently discovered the Baker Framework.

I was wondering if the Baker Framework is still actively maintained as the 6.1 project seems to suggest otherwise.

**Comment by tobiasstrebitzer** [comment]
Baker is still fully functional, and many apps have and are being published.

That being said the project is not actively maintained at the moment due to limited resources. Usually the project becomes more active again when there are breaking changes (e.g. a new, incompatible iOS version).

This topic was recently [discussed here](https://github.com/bakerframework/baker/issues/526).
