### ISSUE TITLE
Is Baker dead?

### ISSUE THREAD

**Issue by carlosajh** [bakerframework/baker#526]
Is Baker dead?

I'm not a developer but i love baker, i'm working as designer for various published magazines. Is Baker dead? The latest commit is from 13 april 2015...

@pieterclaerhout @nin9creative @simbul @folleto @Xm4s @tobiasstrebitzer 

Thanks in advance!

**Comment by nin9creative** [comment]
I personally have been working 60+ hour weeks at my day job for the last 6 months or so...

I know that others have been working quite a bit on their various projects as well.

Hoping to get things moving forward again, but from a feature and application standpoint the platform is still a viable solution.

**Comment by knoxbronson** [comment]
I’ve been publishing a new magazine since May, iPhotographer, based on Baker since April of last year. Baker works fine. 

The only issue was the documentation from Apple and Baker was not up to date about the final stages of creating the app. We hired Andrew to finish it and he did so for a very reasonable fee. Not sure if the documentation is up to date yet.


Knox Bronson
P1xels—The Art of the iPhone
http://pixelsatanexhibition.com
510-612-6124

**Comment by pieterclaerhout** [comment]
I'm afraid it's the same scenario here. I'm currently working on a full time job (at Twixl media) and a side job (photography) which doesn't allow me much time to work on the Baker framework...

**Comment by tobiasstrebitzer** [comment]
As @knoxbronson and @nin9creative mentioned, Baker is still fully functional, and many apps have and are being published.

That being said the project is not actively maintained at the moment due to limited resources. Usually the project becomes more active again when there are breaking changes (e.g. a new, incompatible iOS version).

i'm closing this issue for now. Feel free to reach out in case you need help setting up your app.
