### ISSUE TITLE
Magloft version

### ISSUE THREAD

**Issue by ahvink** [bakerframework/baker#534]
Want to try the MagLoft version of the Baker framework, but the repository can't be used 'out of the box'.

I see a.o. Cocoapods, iRate and Parse, which are all new to me.
Is there somewhere a guide how to set these up so I can check out the MagLoft repository ?

**Comment by travisday** [comment]
Hey @ahvink I just got started into Maglofts version. All you need to do is install cocoa pods. This is the new way they manage the frameworks. Click [here](https://guides.cocoapods.org/using/getting-started.html) to learn about pods and installing it on your computer. Check out maglofts video [here](https://www.youtube.com/watch?v=JZiiqj1_9as&list=WL&index=5) about midway he goes over how to get the pods set up. After that you should be good!

**Comment by nicholasmartin** [comment]
Hi @ahvink thanks for giving it a shot! And a big thanks to @travisday for helping out! We're adding new stuff every day almost so this repo is already quite outdated compared to the latest MagLoft version. Probably about 80% of the things we add also require server side changes which is why it's not easy for us to keep it updated here.

We are also soon launching a freemium version of MagLoft, so you can actually get your magazine apps created completely free in exchange for a little branding in the apps and some very casual ads. I think we will announce the closed launch in this forum and I will try to do my best to offer a special coupon for Baker people :) Stay tuned!

**Comment by ahvink** [comment]
Thanks Travis, ‘ll have a look at that!

Met vriendelijke groeten,
Alfred Vink

Op 22 april 2016 bij 01:56:24, Travis (notifications@github.com) schreef:

Hey @ahvink I just got started into Maglofts version. All you need to do is install cocoa pods. This is the new way they manage the frameworks. Click here to learn about pods and installing it on your computer. Check out maglofts video here about midway he goes over how to get the pods set up. After that you should be good!

**Comment by tobiasstrebitzer** [comment]
Closing this one for now. We'll provide a Setup Guide with the upcoming new version of the MagLoft Baker app.
