### ISSUE TITLE
Disable navigation between pages through swiping or tap

### ISSUE THREAD

**Issue by saminightshift** [bakerframework/baker#562]
I'm trying to disable this function in a standalone app (made in In5 and Indesign, finished off with Baker and Xcode) - I've edited the jquery files and it still functions the same! I went as far as deleting the touchSwipe.min.js file and it still retains that functionality. I should mention that I have buttons within the app that navigate to the pages so we don't want the swiping or tapping at the edges to navigate.

I know if I wanted it to function as a native app I should be creating it as you would an actual app but the company I work for relies on it being done this way. Can anyone help me out on this one?

**Comment by GennadyK** [comment]
This should do it (we use both in some of the books and it works):
-baker-page-turn-tap ( boolean, default: true ) - since 3.2: Defines if you can tap on the right (or left) side to go forward (or back) by one page.
-baker-page-turn-swipe ( boolean, default: true ) - since 3.2: Defines if you can swipe on the page to go forward (or back) by one page.
from here: https://github.com/bakerframework/baker/wiki/Book.json-Baker-extension-parameters

**Comment by saminightshift** [comment]
Perfect thank you!
